name: nationsplus-economy
main: com.ollethunberg.NationsPlusEconomy
version: 0.0.1
api-version: 1.19
author: Olle Thunberg
description: A plugin for NationsPlus that adds an economy
commands:
  balance:
    description: Check your balance
    usage: /<command> <target> <action> [amount]
    aliases: [bal, money, m, b]
  pay:
    description: Pay other players
    usage: /<command> <target> [amount]
    aliases: [pay, p]
  bank:
    description: General bank command
    usage: /<command> <action>
    aliases: [bank]
  banks:
    description: Lists all the banks
    usage: /<command>
    aliases: [banks]
  bankmanager:
    description: Lists all the banks
    usage: /<command> <interest | loans>
    aliases: [bm, bankmanager]
  loans:
    description: Lists all the banks
    usage: /<command> <action>
    aliases: [loans, l, loan]
  close:
    description: Closes the open GUI
    usage: /<command>
    aliases: [close]
  sell:
    description: Sells the item in your hand
    usage: /<command> <amount>
    aliases: [sell, s]
  market:
    description: Opens the market GUI
    usage: /<command>
    aliases: [market, mp]
  listings:
    description: Shows your current active listings on the market
    usage: /<command>
    aliases: [listings, listing, ls]
